version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ml-app"
s3_bucket = "your bucket"
s3_prefix = "ml-app"
region = "eu-west-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repository = "your repo"